### ISSUE TITLE
BongoCat not showing up

### ISSUE THREAD

**Issue by soupglasses** [kitgore/BongoCat#2]
Under both Windows and Linux, VSCode and VSCodium, the BongoCat seems to disappear shortly after install. Being replaced by "ba".

Not sure how to debug this further.

![image](https://github.com/kitgore/BongoCat/assets/20756843/1bca3df9-a917-4fb0-a38b-c5da83b02eb8)

**Comment by kitgore** [comment]
That's weird it's doing that, thanks for letting me know. The animation is done by using custom icons (basically a font) that replaces letters a-d, they should automatically set on download and stay set but clearly it's not sticking for some reason. I'm hoping Command Pallette > "Preferences: Product Icon Theme" > "Bongo Cat Icons" should fix the issue but I'm worried the icons won't stay based on what you're reporting.  I'm wondering if a different extension you have is possibly changing your icon theme or maybe it's something to do with a new version of VSCode. Let me know what happens and hopefully can figure out from there.

**Comment by soupglasses** [comment]
Attemped to do the Command Pallette > "Preferences: Product Icon Theme" > "Bongo Cat Icons. on VSCodium on Linux.

It doesn't sadly seem to help in my instance. Its still not loading in. Unsure of it helps on Windows as that is my friends setup.

**Comment by Dig-pestroyer** [comment]
I can report I am having the same issue. However I know why it's not showing up for me. I have a different **Product Icon Theme** (Material Product Icons) enabled and when I toggle BongoCat, it disables the one I had set and enables the Bongo Cat Icons instead. 

Understandable as to the **_why_** given that it won't allow (as far as I know) two different **Product Icon Themes** to be enabled at the same time. 

What I am trying to figure out is how I can have any Product Icon Theme enabled but still have the BongoCat Icons be persistent, e.g. replace that particular icon with the BongoCat Icons and frankenstein a custom **Product Icon Theme** or possibly restructure BongoCat as an independent extension to allow those icons to be present no matter what **Product Icon Theme** is enabled (if that would even be possible).

**Comment by kitgore** [comment]
@Dig-pestroyer @soupglasses Yeah that makes sense that an icon theme is causing the interference, it is interesting though as Materials is a **File Icon Theme** and BongoCat is a **Product Icon Theme** and at least in my VSCode, the two are set under separate commands (Preferences: File Icon Theme, Preferences: Product Icon Theme) which I would think would prevent them from interfering in the first place. 

I have a few ideas I want to try but unfortunately I've been unsuccessful trying to replicate the issue on either of my systems (Arch Linux and Windows), using different icon themes and enabling/disabling them. The icon theme got disabled on my friend's Mac as well but doing the command I suggested above fixed the issue on his. I'll look into how other extensions handle custom icons and see if I'm doing anything differently but it may be an issue with VSCode as I believe this just started occurring recently. Let me know if either of you would want to help me try out some fixes this weekend or another time as I can't really do much testing on my own

**Comment by Dig-pestroyer** [comment]
@kitgore I was curious and went to double check but what I was referring to is indeed installed under the name **Material Product Icons** but I also have **Material Icon Theme** installed as well.

[Material Product Icons](https://open-vsx.org/extension/PKief/material-product-icons) | [Material Icon Theme](https://open-vsx.org/extension/PKief/material-icon-theme)

![image](https://github.com/kitgore/BongoCat/assets/15187592/f1b624fb-b7b2-4028-82ed-b30017418c17)

**Comment by dimateos** [comment]
Maybe the command "Toggle Bongo Cat" (extension.toggleStatusBar) -> should set the "product icon theme" if thats possible.

Idk why an update reset my "product icon theme" and I lost the bongo cat, had to search for issues to find this solutio.

I dont even have any other "product icon theme" installed:
![image](https://github.com/kitgore/BongoCat/assets/26868611/38218b3d-04e7-4629-907d-95ba5188dad1)

> I have a few ideas I want to try but unfortunately I've been unsuccessful trying to replicate the issue on either of my systems

This issue seems to only happen when other "product icon theme" is set. Nothing to do with mixing the active "file icon theme" (I use "Material Icon theme", not the product icon theme), hence thats why u cannot reproduce.

Not sure if mixing or patching the active "product icon theme" is possible.
Maybe the command could set the "product icon theme" and log a bubble message with a warning if it was not the default (or always) to report the incompatibility.

Best regards

**Comment by farisfaikar** [comment]
I've had the same issue as OP where the BongoCat was replaced by "ba" a while ago and since then I've disabled Bongo Cat. Now, I'm returning to the extension to re-enabled and I've noticed that it's just completely gone now, nowhere to be seen. I've tried reinstalling the extension and running "Toggle Bongo Cat", but it doesn't show up. I'm also using Bongo Cat Icons. What could be causing the issue?
